name: _tf-deploy-reusable
permissions:
  id-token: write
  contents: read

on:
  workflow_call:
    inputs:
      module_path:
        required: true
        type: string
      aws_region:
        required: true
        type: string
      extra_tfvars:
        required: false
        type: string
        default: ''
    secrets:
      AWS_ROLE_TO_ASSUME:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}

    steps:
      - name: Bootstrap for all workflows
        uses: ./.github/actions/bootstrap-pipeline
        with:
          aws_region: ${{ inputs.aws_region }}
          aws_role_to_assume: ${{ env.AWS_ROLE_TO_ASSUME }}

      - name: Terraform Init
        working-directory: ${{ inputs.module_path }}
        run: |
          if [ -f backend.hcl ]; then
            terraform init -reconfigure -backend-config=backend.hcl
          else
            terraform init -backend=false
          fi

      - name: Terraform Validate
        working-directory: ${{ inputs.module_path }}
        run: terraform validate

      - name: Write backend configs
        run: ./scripts/write-backend-config.sh
        
      - name: Terraform Apply
        working-directory: ${{ inputs.module_path }}
        run: |
          ARGS=""
          if [ -n "${{ inputs.extra_tfvars }}" ]; then
            ARGS='${{ inputs.extra_tfvars }}'
          fi
          terraform apply -input=false -auto-approve $ARGS
